version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout

      - run:
          name: Set up Python environment
          command: |
            python3 -m venv venv
            source venv/bin/activate || . venv/Scripts/activate

      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt

      - run:
          name: Run unit tests
          command: |
            pytest

workflows:
  version: 2

  main-branch-workflow:
    jobs:
      - upload-project-on-s3:
          filters:
            branches:
              only: main
